language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: q3X7F+6X/nCc7MyaI5pqg5P5AhM8O8SPiKf3JROiX9fcSWplzwDp4AOM5qF6vnYbZrklIzGYUGJEZwpvpzPQ2S3bt0y3+eGTIOmVB+RCfxucS2VNQnhxFDO+4EK39ymuq+Ww+hzMLPt8MG9BM5fP8jp42NnDvGsMqbb+RpsXeY5cnYtvLPNvzEw3iREKKYBfhv4eqR8vEv+sY6x5Pod/MF02neN710eAVdogJPNNhe5nG+G8pPcq/B2/6Whgaj8wQd6ElghmBs2NnJcWHhD1iYsPAsiQpmdonXFUQP9gaIU/ecxjaHGT9iC5GsAPXawPXDaRrJ2bEOHRENAcbTYa+WazkN0r0A+kEPavB5FyFHflVerYg9Yt4GxqaLLbIuEMEO3ZLHduR447hqDNawEAZZmBT+PBZ6FhOkdmQA4DyjVwkgpF/7CK0j6IHZdW7njBVo8CbTVhZbOjUkXOnS+EvYHEYK1AcsVyTAQenwPT84QGZe/2f/ZBg6YSyKGKrODWge3v8/ByVRpdxULdjDbGBG59QasAJAIq7MJG2ZR+o9BuploOLO9f39i4XCRYiAzpQXS/eoWcqx9IcX4df245KpLkkgA/TCb1vCG8STKzESoU0BDvUu3j6miIVVgEv0RMR1QFSweC9Eea0XHuFKSjnIEernFzmZItpR8YoQZ03d8=
  on:
    tags: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
